# Generated by Django 3.1.5 on 2022-05-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foto',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='contacto',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='detail',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Información del producto'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
